name: Cicd
on:
    push:
        branches: [main]
jobs:
    sonar:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              run: ls -la # lister tous les fichiers qui sont sur le runner